improve(ProviderUtils): Remove log about cache provider
This log is noisy and has a bug sometimes. I'm not sure the cause of this, but regardless this log isn't as helpful as I thought it'd be.

```
TypeError: Cannot read properties of null (reading '1')
    at new CacheProvider (/Users/nicholaspai/UMA/relayer-v2/src/utils/ProviderUtils.ts:129:22)
    at /Users/nicholaspai/UMA/relayer-v2/src/utils/ProviderUtils.ts:261:19
    at Array.map (<anonymous>)
    at new RetryProvider (/Users/nicholaspai/UMA/relayer-v2/src/utils/ProviderUtils.ts:260:29)
    at getProvider (/Users/nicholaspai/UMA/relayer-v2/src/utils/ProviderUtils.ts:566:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBlockFinder (/Users/nicholaspai/UMA/relayer-v2/src/utils/BlockUtils.ts:14:30)
    at async getBlockForTimestamp (/Users/nicholaspai/UMA/relayer-v2/src/utils/BlockUtils.ts:34:19)
    at async /Users/nicholaspai/UMA/relayer-v2/src/common/ClientHelper.ts:81:28
    at async Promise.all (index 4)
    at async constructSpokePoolClientsWithLookback (/Users/nicholaspai/UMA/relayer-v2/src/common/ClientHelper.ts:76:5)
    at async constructFinalizerClients (/Users/nicholaspai/UMA/relayer-v2/src/finalizer/index.ts:218:28)
    at async Object.runFinalizer [as finalizer] (/Users/nicholaspai/UMA/relayer-v2/src/finalizer/index.ts:262:47)
    at async run (/Users/nicholaspai/UMA/relayer-v2/index.ts:55:9)
```